#!/usr/bin/python

import glob
import importlib
import os
import pwd
import re
import sys



class ERROR_CODE:
    SUCCESS = 0

    # Python uses exit-code 1 as a generic exit-code during exceptions.
    # We want to avoid using this exit-code in our code.
    GENERIC_EXCEPTION = 1

    INVALID_INPUT = 2
    PLUGIN_FAILED = 3
    WRITE_FAILED = 4
    USER_ABORTED = 5
    FILE_NOT_FOUND = 6
    CANNOT_PROCESS_HOSTS_FILE = 7


class Version:
    MAJOR = 1
    MINOR = 2
    PATCH = 1
    META = 'dev'

    @classmethod
    def get(cls):
        version = str(cls.MAJOR) + \
                  '.' + str(cls.MINOR) + \
                  '.' + str(cls.PATCH)

        if len(cls.META) > 0:
            version += '-' + cls.META

        return version


# constants - START

VERSION = Version.get()

SUPPORTED_ARGS = (
    '-v',
    '--version',

    'build',
    'clean',
    'clean-all'
)

USER_ID = os.getuid()
USER_NAME = pwd.getpwuid(USER_ID).pw_name

# get the command line input arguments into a var
INPUT_ARGS = sys.argv
INPUT_ARGS_COUNT = len(INPUT_ARGS)
PRIMARY_COMMAND = INPUT_ARGS[1]

SCRIPT_NAME = INPUT_ARGS[0]
SCRIPT_PATH = os.path.realpath(SCRIPT_NAME)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)

CONFIG_FILE_NAME = 'config.py'

# constants - END


# methods - START

def cannot_process_hosts_file():
    # For some reason or the other the input
    # hosts file could not be processed.
    # Show an error to the user and abort.
    print "\nThe input hosts file does NOT have the correct order of 'tkhm' delimiters."
    print "Cannot process further. Aborting!\n"
    sys.exit(ERROR_CODE.CANNOT_PROCESS_HOSTS_FILE)


def clean_hosts_file(clean_all=False):
    print 'Cleaning hosts file'

    if clean_all:
        print '\tClean all = Y\n'
        print '\tTHIS WILL CLEAR THE HM HOSTS-CONFIG FOR ALL USERS.'

        confirm = None

        try:
            # python 2.7+
            confirm = raw_input('\tAre you sure you want to do this? [y/N] ')
        except Exception:
            # python 3+
            confirm = input('\tAre you sure you want to do this? [y/N] ')

        if confirm.lower() != 'y':
            print '\nAborted by the user!\n'
            sys.exit(ERROR_CODE.USER_ABORTED)


    global hosts_file

    cleaned_hosts_file = []
    write = True
    skip_blank_lines = False
    pattern = None

    if clean_all:
        pattern = "^# tkhm - .*? - (START|END)$"
    else:
        pattern = "^# tkhm - %s - (START|END)$" % USER_NAME


    for i in range(0, len(hosts_file)):
        line = hosts_file[i]

        match = re.match(pattern, line)

        if match:
            if (match.group(1) == 'START' and not write) \
                or (match.group(1) == 'END' and write):
                # The delimiters are screwed up; abort
                cannot_process_hosts_file()

            if write:
                while len(cleaned_hosts_file) > 0 and re.sub('[\s\n]+', '', cleaned_hosts_file[-1]) == '':
                    cleaned_hosts_file.pop()

                # leave a courtesy new-line
                cleaned_hosts_file.append('\n')
            else:
                skip_blank_lines = True

            write = not write
            continue

        if skip_blank_lines and re.sub('[\s\n]+', '', line) == '':
            continue

        skip_blank_lines = False

        if not write:
            continue

        cleaned_hosts_file.append(line)

    if not write:
        # This shouldn't happen.
        # Once the END delimiter is reached the flag is switched
        # to 'write = True' again.
        # This means the delimiters are screwed up; abort
        cannot_process_hosts_file()

    hosts_file = cleaned_hosts_file

    try:
        with open(config.output_file_path, "w") as f:
            f.write(
                ''.join(hosts_file)
            )

    except Exception, err:
        print "\t%s\nFailed\n" % err
        sys.exit(ERROR_CODE.WRITE_FAILED)
    else:
        print "Done\n"

    return


def import_module_from_file(file_name):
    module_name = re.sub('\.py', '', file_name)
    module_name = re.sub('/', '.', module_name)

    module = importlib.import_module(module_name)

    return module


def is_ipv4(str):
    match = re.match("^(?:[1]?[\d]{1,2}|2[0-4][\d]|25[0-5])\.(?:[1]?[\d]{1,2}|2[0-4][\d]|25[0-5])\.(?:[1]?[\d]{1,2}|2[0-4][\d]|25[0-5])\.(?:[1]?[\d]{1,2}|2[0-4][\d]|25[0-5])$", str)

    if match:
        return True

    return False


def load_config():
    if not os.path.isfile(CONFIG_FILE_NAME):
        print 'Config file not found - Aborting'
        sys.exit(ERROR_CODE.FILE_NOT_FOUND)

    config = import_module_from_file(CONFIG_FILE_NAME)
    print 'Config file loaded\n'
    return config


def load_manual_hosts_map_config():
    hosts_map_files = glob.glob('hosts_maps/*_conf.py')

    print 'Loading host-map files:'

    for hosts_map_file in hosts_map_files:
        print "\t%s" % hosts_map_file

        map_file_base_name = os.path.basename(hosts_map_file)

        module = import_module_from_file(hosts_map_file)

        hosts_map_config = {}

        try:
            hosts_map_config[map_file_base_name] = module.hosts_map_config
        except AttributeError:
            # < v1.2
            hosts_map_config[map_file_base_name] = module.host_map_config

        update_hosts_map('manual-hosts-maps', hosts_map_config)

    print "Done - %s file(s) loaded\n" % len(hosts_map_files)

    return


def load_plugins():
    active_plugins = config.active_plugins

    print 'Active-plugins:'

    for plugin_name in active_plugins:
        print "\t%s" % plugin_name

    print "%s plugin(s) active\n" % len(active_plugins)

    for plugin_name in active_plugins:
        print "Running: '%s'" % plugin_name

        plugin_config = {}

        if plugin_name in config.plugin_config:
            plugin_config = config.plugin_config[plugin_name]

        try:
            plugin = import_module_from_file("plugins/%s/main.py" % plugin_name)

            print "%s v%s" % (plugin.DISPLAY_NAME, plugin.VERSION)

            hosts_map_config = plugin.main(plugin_config)

            update_hosts_map(plugin_name, hosts_map_config)

        except Exception, err:
            print "\t%s\nFailed\n" % err
            sys.exit(ERROR_CODE.PLUGIN_FAILED)

        else:
            print "Done\n"

    return


def print_valid_args():
    print "\nValid arguments are:\n%s" % '\n'.join(SUPPORTED_ARGS)


def process_hosts_maps(hosts_map, prefix=None):

    processed_hosts_map = []

    ip_entries = {}
    nested_hosts_map = []

    hosts_count = 0

    hosts_map_items = hosts_map.items()


    for (key, val) in hosts_map_items:
        if isinstance(val, dict):
            # nested config
            if prefix == None:
                cur_prefix = key
            else:
                cur_prefix = "%s - %s" % (prefix, key)

            ret_val = process_hosts_maps(val, cur_prefix)

            hosts_count += ret_val['hosts_count']

            if prefix == None:
                nested_hosts_map += [ '\n' ]

            nested_hosts_map += ret_val['hosts_map']

            if prefix == None:
                nested_hosts_map += [ '\n' ]
        elif is_ipv4(key):
            # assume hosts-list

            if key in ip_entries:
                curr_ip_entries = ip_entries[key]
            else:
                curr_ip_entries = set([])

            curr_hosts_lists = set(val)

            hosts_count += len(curr_hosts_lists)

            curr_ip_entries.update(curr_hosts_lists)

            ip_entries[key] = curr_ip_entries
        else:
            # we do NOT expect to be here
            raise ValueError('Could not parse. Possible bad config values.', key, val)

    if hosts_count > 0:

        ip_entries_items = ip_entries.items()
        ip_entries_count = len(ip_entries_items)

        if prefix != None and ip_entries_count > 0:
            processed_hosts_map += [ '# %s - START\n' % prefix, '\n' ]



        for (ip, host_names) in ip_entries_items:
            ip_length = len(ip)

            tabs = '\t'

            # calculate tabs assuming ipv4 mapping
            if ip_length < 8:
                tabs *= 3
            elif ip_length < 12:
                tabs *= 2

            processed_hosts_map += [ "%s%s%s\n" % (ip, tabs, ' '.join(host_names)) ]

        # if len(ip_entries_items) == 0 and len(processed_hosts_map) > 0:
        #     if processed_hosts_map[-1] == '\n':
        #         processed_hosts_map.pop()

        processed_hosts_map += nested_hosts_map

        if prefix != None and ip_entries_count > 0:
            processed_hosts_map += [ '\n', '# %s - END\n' % prefix, '\n' ]

    return {
        "hosts_count": hosts_count,
        "hosts_map": processed_hosts_map
    }


def verify_supported_args():
    unsupported_args = []

    if INPUT_ARGS_COUNT <= 1:
        print 'No arguments supplied'
        print_valid_args()
        sys.exit(ERROR_CODE.INVALID_INPUT)

    if INPUT_ARGS_COUNT > 2:
        print 'Too many arguments supplied'
        print_valid_args()
        sys.exit(ERROR_CODE.INVALID_INPUT)

    for i in range(1, INPUT_ARGS_COUNT):
        arg = str(INPUT_ARGS[i])

        if not arg in SUPPORTED_ARGS:
            unsupported_args.append(arg)

    if len(unsupported_args) > 0:
        print "Invalid input. The following arguments are not supported:\n%s" % '\n'.join(unsupported_args)
        print_valid_args()
        sys.exit(ERROR_CODE.INVALID_INPUT)


def read_hosts_file():
    hosts_file = []
    print "Reading hosts file at:\n\t%s" % config.hosts_file_path

    with open(config.hosts_file_path, "r") as f:
        hosts_file = f.readlines()

    print 'Done\n'

    return hosts_file


def update_hosts_map(map_key, hosts_map_config):
    global hosts_map

    curr_hosts_map = {}

    if map_key in hosts_map:
        curr_hosts_map = hosts_map[map_key]

    for (key, value) in hosts_map_config.items():
        curr_hosts_map[key] = value

    hosts_map[map_key] = curr_hosts_map

    return


def write_hosts_file():
    global hosts_file
    global hosts_map


    hosts_count = 0

    hosts_file += [
        '\n\n\n',
        "# tkhm - %s - START\n" % USER_NAME
    ]

    ret_val = process_hosts_maps(hosts_map)

    hosts_count = ret_val['hosts_count']
    hosts_file += ret_val['hosts_map']

    hosts_file += [
        '\n',
        "# tkhm - %s - END\n" % USER_NAME,
        '\n\n'
    ]

    if hosts_count == 0:
        print 'Host map is empty. Nothing to do!\nExiting'
        sys.exit(ERROR_CODE.SUCCESS)

    print "Writing hosts file:\n\t%s" % config.output_file_path

    try:
        with open(config.output_file_path, "w") as f:
            f.write(
                ''.join(hosts_file)
            )

    except Exception, err:
        print "\t%s\nFailed\n" % err
        sys.exit(ERROR_CODE.WRITE_FAILED)
    else:
        print "Done\n"

    return


# methods - END


# regular program from this point on

config = None
hosts_map = {}
hosts_file = None


# need to do this in-case the executable is symlinked
os.chdir(SCRIPT_DIR)


verify_supported_args()


if PRIMARY_COMMAND in ('-v', '--version'):
    print VERSION
    sys.exit(ERROR_CODE.SUCCESS)


print "TK host manager v%s\n" % VERSION


config = load_config()

hosts_file = read_hosts_file()


if PRIMARY_COMMAND == 'clean-all':
    clean_hosts_file(True)
    sys.exit(ERROR_CODE.SUCCESS)


clean_hosts_file()


if PRIMARY_COMMAND == 'clean':
    # already done cleaning; exit
    sys.exit(ERROR_CODE.SUCCESS)

if PRIMARY_COMMAND != 'build':
    # We shouldn't be here if the `verify_supported_args` method
    # did it's job correctly but since we are here, exit with an
    # error code.
    sys.exit(ERROR_CODE.INVALID_INPUT)


# only executing the `build` command from here on out

load_manual_hosts_map_config()
load_plugins()
write_hosts_file()

sys.exit(ERROR_CODE.SUCCESS)


